nnoremap <leader>ws :split<CR>
nnoremap <leader>wv :vsplit<CR>
nnoremap <leader>wo :only<CR>
nnoremap <leader>wd :close<CR>
nnoremap <leader>ww <C-w>w
nnoremap <leader>w= <C-w>=
nnoremap <leader>wh <C-w>H
nnoremap <leader>wl <C-w>L
nnoremap <leader>wj <C-w>J
nnoremap <leader>wk <C-w>K
