#! /bin/sh


# Launch UI services
# -----------------------------------------------------

# Keboard shortcuts manager
sxhkd &

# Increase the mouse wheel speed (conf file is in ~/.imwheelrc)
imwheel

# Clipmenu
clipmenud &

# Polybar
$HOME/.config/polybar/launch.sh

# Animations
picom --config ~/.picom.conf &

# Background
if [[ -f "$HOME/.cache/wal/sequences" ]]; then
    # Color schemas
    wal -R

    # Import the colors.
    . "${HOME}/.cache/wal/colors.sh"
else
    # Background
    nitrogen --set-centered /usr/share/backgrounds/custom/default.jpg &
fi

# -----------------------------------------------------


# BSPWM Config
# -----------------------------------------------------
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config presel_feedback_color \#404040

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc rule -a Evolution desktop='^10' follow=on
bspc rule -a Skype desktop='^9' follow=on
bspc rule -a TelegramDesktop desktop='^9' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a rawtherapee desktop='^8' follow=on
bspc rule -a Screenkey manage=off
# bspc rule -a jetbrains-idea desktop='^4' follow=on
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# -----------------------------------------------------
