#! /bin/sh


# Launch UI services
# -----------------------------------------------------

# Keboard shortcuts manager
sxhkd &

# Increase the mouse wheel speed (conf file is in ~/.imwheelrc)
# imwheel

# Clipmenu
clipmenud &

# Network Manager Agent
# nm-applet --sm-disable &
# nm-applet &

# Hide Cursor when typing
# xbanish &

# Background
if [[ ! -f $HOME/.cache/nitrogen/current_wallpaper ]]; then
    nitrogen --set-scaled /usr/share/backgrounds/custom/default.jpg
else
    nitrogen --set-scaled `cat $HOME/.cache/nitrogen/current_wallpaper`
fi

# Polybar
$HOME/.config/polybar/launch.sh

# Animations
picom --config ~/.picom.conf &

# -----------------------------------------------------


# BSPWM Config
# -----------------------------------------------------
internal_display=$(xrandr | grep ' connected' | grep 'primary' | awk '{print $1}')
external_display=$(xrandr | grep ' connected' | grep -ve 'primary' | awk '{print $1}')

[[ -f "/tmp/EXTERNAL_MONITOR" ]] && external_display_mode=$(cat /tmp/EXTERNAL_MONITOR)

# if HDMI1 Connected, then start second external polybar
if [[ ! -z "$external_display" && "$external_display_mode" == 'dual' ]]; then
    bspc monitor $external_display -d 1 2 3
    bspc monitor $internal_display -d 4 5 6 7 8 9 10
else
    bspc monitor $internal_display -d 1 2 3 4 5 6 7 8 9 10
fi


bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color "#404040"
bspc config focused_border_color "#adadb2"
# bspc config normal_border_color "#44475a"
# bspc config active_border_color "#ffffff"


bspc rule -a Skype desktop='^10' follow=on
bspc rule -a slack desktop='^10' follow=on
bspc rule -a teams desktop='^10' follow=on
bspc rule -a TelegramDesktop desktop='^10' follow=on
bspc rule -a viber desktop='^10' follow=on
bspc rule -a Evolution desktop='^9' follow=on
# bspc rule -a Gimp desktop='^6' follow=on
# bspc rule -a rawtherapee desktop='^8' follow=on
bspc rule -a Screenkey manage=off
#bspc rule -a 0x260002f state=floating
# -----------------------------------------------------
