make all
make run
make debug
make build
make clean
make test
make docker-build-latest
make docker-build-snapshot
make docker-build-release
make docker-push-latest
make docker-push-snapshot
make docker-push-release
