#!/bin/bash
#
# ~/.xinitrc


# Set the keyboard repeat and delay
xset r rate 200 100

# Remap caps lock to escape
setxkbmap -option caps:escape

# Swap mouse for left handed
xmodmap -e "pointer = 3 2 1 4 5 6 7 8 9 10"

export PATH="$PATH:$HOME/.local/bin"

xdg-settings set default-web-browser firefox.desktop
