#!/bin/bash
#
# ~/.xprofile

# ENV variable needed by X window
# --------------------------------

# Needed by Intellij to open the window correctly
export _JAVA_AWT_WM_NONREPARENTING=1

# Used for Java AWT UI settings
# export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true ${_JAVA_OPTIONS}"

# --------------------------------


# Set the keyboard repeat and delay
xset r rate 200 100

# Remap caps lock to escape
setxkbmap -option caps:escape

# Remap alt to win
setxkbmap -option altwin:swap_alt_win

# Swap mouse for left handed
xmodmap -e "pointer = 3 2 1 4 5 6 7 8 9 10"

