#!/bin/bash
#
# ~/.xinitrc

# ENV variable needed by X window
export PATH="$PATH:$HOME/.local/bin"
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
export _JAVA_AWT_WM_NONREPARENTING=1
# export SUDO_ASKPASS=$HOME/.config/bin/dmenu-ask-pass.sh


# Set the keyboard repeat and delay
xset r rate 200 100

# Remap caps lock to escape
setxkbmap -option caps:escape

# Remap alt to win
setxkbmap -option altwin:swap_alt_win

# Swap mouse for left handed
xmodmap -e "pointer = 3 2 1 4 5 6 7 8 9 10"

# Increase the mouse wheel speed (conf file is in ~/.imwheelrc)
imwheel

# Enable clipboard manager
clipmenud &


